#!/bin/bash

# args:
# ./generate <name> <command> <dir>
# e.g
# ./generate remapper "./gradlew javadoc" ../build/docs/javadoc

name=$1
command=$2
dir=$3
echo "Running command..."
${command} && {
    echo "Finished running command."
    echo "Deploying..."
    git config user.name "Lapislazuli"
    git config user.email "lapislazuli@lapis.blue"
    git rm -r ${name}
    cp -r ${dir} ${name}
    git add -A
    git commit -m "Update to $TRAVIS_REPO_SLUG@$TRAVIS_COMMIT (Build $TRAVIS_BUILD_NUMBER)"
    git push origin gh-pages
    echo "Finished deploying."
}